### ISSUE TITLE
Doesn't work on windows  spawn ENOENT

### ISSUE THREAD

**Issue by acierto** [teerapap/grunt-protractor-runner#118]
Updated to "grunt-protractor-runner": "2.0.0", on linux there is no issues but on windows happen the exception pasted below. Could be any conflicts with internal libraries specific to Windows or some extra onces should be installed?

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
  at errnoException (child_process.js:1000:11)
  at Process.ChildProcess._handle.onexit (child_process.js:791:34)

>> events.js:72
>>         throw er; // Unhandled 'error' event
>>               ^
>> Error: spawn ENOENT
>>   at errnoException (child_process.js:1000:11)
>>   at Process.ChildProcess._handle.onexit (child_process.js:791:34)

**Comment by justinhelmer** [comment]
getting the same issue, specifically on windows. works on osx and linux

**Comment by danigonlinea** [comment]
I was investigating on that I and it is happening the same to me. I realice that the problem is when you load the tests, chromeDriver is automatically call, open browser specified and do testing. 

To integrate with "grunt-protractor-runner", I had to put this property on protractor conf.js 'directConnect: false' and start webdriver manually (webdriver-manager start). After this just run your testing cases with grunt, and you will see that it is correctly tested.

**Comment by justinhelmer** [comment]
@danigonlinea thank you for this information. I will hand it off to my team and those with `Windows` can give it a try (although I think our guys are all on `Linux` now).

Thanks for reporting your findings.

**Comment by Wolfium** [comment]
I know it is a bit late, but solucion might help someone...

To figure out the real issue just install protractor global and run it globaly from any directory without any config js file, it stated that JAVA was not found, and it was, I removed JAVA completely from my windows installation.

Once I reinstalled JAVA and open a new command window with JAVA available protractor ran and informed that there were no configuration.

Going back to the proyect directory all run fine then.

Regards
