### ISSUE TITLE
When running webdriver - error 'Server terminated early with status 2'

### ISSUE THREAD

**Issue by jlongie** [teerapap/grunt-protractor-runner#150]
Hi,

Getting  the following exception when I try to execute protractor:

npm -v = 2.14.2
node -v = 0.12.7
grunt-protractor-runner = 2.1.2

```sh
/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857
      var result = fn();
                   ^
Error: Server terminated early with status 2
    at Error (native)
    at /build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/remote/index.js:204:25
    at [object Object].promise.ControlFlow.runInFrame_ (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:1857:20)
    at [object Object].goog.defineClass.notify (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:2448:25)
    at [object Object].promise.Promise.notify_ (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:564:12)
    at Array.forEach (native)
    at [object Object].promise.Promise.notifyAll_ (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/../webdriver/promise.js:553:15)
    at goog.async.run.processWorkQueue (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/goog/async/run.js:130:15)
    at runMicrotasksCallback (node.js:337:7)
    at process._tickCallback (node.js:355:11)
From: Task: WebDriver.createSession()
    at Function.webdriver.WebDriver.acquireSession_ (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:157:22)
    at Function.webdriver.WebDriver.createSession (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/lib/webdriver/webdriver.js:131:30)
    at new Driver (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/selenium-webdriver/chrome.js:810:36)
    at [object Object].DirectDriverProvider.getNewDriver (/build/node_modules/grunt-protractor-runner/node_modules/protractor/lib/driverProviders/direct.js:68:16)
    at [object Object].Runner.createBrowser (/build/node_modules/grunt-protractor-runner/node_modules/protractor/lib/runner.js:182:37)
    at /build/node_modules/grunt-protractor-runner/node_modules/protractor/lib/runner.js:263:21
    at _fulfilled (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:797:54)
    at self.promiseDispatch.done (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:826:30)
    at Promise.promise.promiseDispatch (/build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:759:13)
    at /build/node_modules/grunt-protractor-runner/node_modules/protractor/node_modules/q/q.js:525:49
[launcher] Process exited with error code 1

```

The command is

```sh
bb_xvfb.sh grunt test:e2e --cucumberTags="@flow" --no-color
```

The bb_xvfb.sh looks like the following:

```
#!/bin/bash
set -ex

# Note: "32" is not a valid depth for xvfb: https://bugs.freedesktop.org/show_bug.cgi?id=17453 (from 2008)
SCREEN_SIZE="1920x1200x24+32"

BINDIR="$(dirname $0)"
TMPDIR=/tmp

if [ ! -d "$TMPDIR" ]; then
    echo "Invalid tmp directory: ${TMPDIR}"
    exit 1
fi

# Avoid race conditions in google-chrome startup by making sure there is a
# dbus message bus up and running.
# See https://code.google.com/p/chromium/issues/detail?id=309093
DBUS="dbus-launch --exit-with-session"

XVFBDIR="${TMPDIR}/xvfb.$$"
mkdir -p "${XVFBDIR}"

ERRFILE="${XVFBDIR}/xvfb.log"

# Pass the "-fbdir" to force xvfb to use a memory-mapped file.  This makes screenshots and debugging easier.
# To display said framebuffer contents: xwud -in ${XVFBDIR}/Xvfb_screen0

exec xvfb-run \
    --error-file="${ERRFILE}" \
    --auto-servernum \
    --server-args=" -screen 0 ${SCREEN_SIZE} -dpi 96 -ac" \
    ${WAITFORX} ${DBUS} "$@"

#eof
```

**Comment by jlongie** [comment]
After a day of investigation the problem was the following:

In our protractor config file, we specify the path to the chromeDriver, as shown:
```sh
    chromeDriver:'../node_modules/chromedriver/lib/chromedriver/chromedriver',
```

We have a wrapper for this node module which manages our third party dependencies. When the install of the node modules was done and migrated over to our docker container it had the wrong binary for the OS! Doing a fresh install on the OS resolved the problem.

**Comment by stoich** [comment]
I've hit the same exception when working with selenium-webrdriver on node. It's **npm install** that's causing it.  That operation setups up some environmental stuff (local path to runner) that will vary with our OS. 

Running **npm install** on MAC and running it on Linux will setup some of the bindings in **node_modules** differently. 

What was happening was I had done npm install locally on OSX. Then I was running from the same folder via Wercker on a Linux docker image. But on the Docker instance **npm install** would detect that I already had the modules and it just moved on to running the app. 

And at that point it threw **Server terminated early with status 2**. Deleting **node_modules** folder and letting **npm install** re-populate it solved the issue for me.

**Comment by TransportSolutions** [comment]
Thank you @stoich
