### ISSUE TITLE
node webdriver-manager update throwing syantax error

### ISSUE THREAD

**Issue by JoeDevi** [teerapap/grunt-protractor-runner#170]
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

Did not see any syntax error infact in webdriver-manager file!

**Comment by ThomasStubbe** [comment]
Same problem, windows-specific

**Comment by iamtheddrman** [comment]
Running into the same problem. More than a year, but no response or workaround?
