### ISSUE TITLE
Cannot find chrome Driver on grunt protractor

### ISSUE THREAD

**Issue by ColinPacitti** [teerapap/grunt-protractor-runner#45]
When I run protractor with 
$protractor config/e2e.conf.js
It works without a problem but when I try to run it when grunt I get a chrome driver not found error

/Users/Alfred/Development/git/f1/Web/f1/test/node_modules/protractor/lib/driverProviders/local.dp.js:42
        throw new Error('Could not find chromedriver at ' +
              ^
Error: Could not find chromedriver at /Users/Alfred/Development/git/f1/Web/f1/test/node_modules/protractor/selenium/chromedriver.exe
    at LocalDriverProvider.addDefaultBinaryLocs_ (/Users/Alfred/Development/git/f1/Web/f1/test/node_modules/protractor/lib/driverProviders/local.dp.js:42:15)
    at LocalDriverProvider.setupEnv (/Users/Alfred/Development/git/f1/Web/f1/test/node_modules/protractor/lib/driverProviders/local.dp.js:59:8)
    at Runner.run (/Users/Alfred/Development/git/f1/Web/f1/test/node_modules/protractor/lib/runner.js:308:31)
    at process.<anonymous> (/Users/Alfred/Development/git/f1/Web/f1/test/node_modules/protractor/lib/runFromLauncher.js:32:14)
    at process.EventEmitter.emit (events.js:98:17)
    at handleMessage (child_process.js:318:10)
    at Pipe.channel.onread (child_process.js:345:11)
[launcher] Runner Process Exited With Error Code: 8

> > Fatal error: protractor exited with code: 1

Heres my config file:

```
    protractor: {
        options: {
            configFile: "config/e2etest.conf.js",
            keepAlive: false,
        },
        chrome: {
            options: {
                args: {
                    browser: "chrome"
                }
            }
        },
        firefox: {
            options: {
                args: {
                    browser: "firefox"
                }
            }
        },
        safari: {
            options: {
                args: {
                    browser: "safari"
                }
            }
        }
    }
```

**Comment by F1LT3R** [comment]
@froots `./node_modules/grunt-protractor-runner/node_modules/protractor/bin/webdriver-manager update` worked for as well. Thanks!

**Comment by EallanW** [comment]
I download the chorme driver and unzip it from the following link, then I fixed this problem.
http://chromedriver.storage.googleapis.com/index.html?path=2.10/

**Comment by hasanyousuf** [comment]
add these lines of code to your package.json
  "scripts": {
    "install": "node node_modules/protractor/bin/webdriver-manager update"
  },
It works like a charm for me
